AccessCorpFormulario.Web/Models/MockModelView.cs
using AccessCorpFormulario.Domain.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;

namespace AccessCorpFormulario.Web.Models
{
    public static class MockModelView
    {

        public static List<FormularioModelView> MockListaFormularioModelView()
        {
            return new List<FormularioModelView>
            {
                new FormularioModelView
                {
                    IdFormulario = 1,
                    DataVencimentoFim = "01/05/2020",
                    DataVencimentoInicio = "01/01/2018",
                    NomeFormulario = "Cadastro de Usuário"
                },
                new FormularioModelView
                {
                    IdFormulario = 2,
                    DataVencimentoFim = "18/08/2022",
                    DataVencimentoInicio = "20/10/2020",
                    NomeFormulario = "Cadastro de Roupas"
                }
            };
        }

        public static List<ListItem> ListaTipoCampo()
        {
            return
                new List<ListItem>{
                new ListItem { Text = "-- Selecionar --", Value = "" },
                 new ListItem { Text = "Textbox", Value = "1" },
                new ListItem { Text = "Dropbox", Value = "2" },
                new ListItem { Text = "Radio Button", Value = "3" }
        };
        }

        public static List<ListItem> ListaTipoValorCampo()
        {
            return
                new List<ListItem>{
                new ListItem { Text = "-- Selecionar --", Value = "" },
                new ListItem { Text = "Texto", Value = "1" },
                new ListItem { Text = "Numérico", Value = "2" },
                new ListItem { Text = "Moeda", Value = "3" }
        };
        }
    }
}

AccessCorpFormulario.Web/Controllers/FormularioController.cs
using AccessCorpFormulario.AplicationService.Service.Interfaces;
using AccessCorpFormulario.Domain.ModelView;
using AccessCorpFormulario.Web.Models;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AccessCorpFormulario.Web.Controllers
{
    public class FormularioController : Controller
    {
        IFormularioApplicionServie _formularioApplicionServie;

        public FormularioController(IFormularioApplicionServie formularioApplicionServie)
        {
            _formularioApplicionServie = formularioApplicionServie;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Cadastro()
        {
            var model = new CadastroFormularioCampoModelView();
            
            model.ListaTipoCampo = MockModelView.ListaTipoCampo();
            model.ListaTipoValorCampo = MockModelView.ListaTipoValorCampo();

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> Lista()
        {
            var lista  = await _formularioApplicionServie.List();

            return View(lista.ToList());
        }

        [HttpGet]
        public ActionResult Exibir(int id)
        {
            var formulario = _formularioApplicionServie.GetById(id);

            return View(formulario);
        }

    }
}

AccessCorpFormulario.Web/Views/Formulario/Cadastro.cshtml
@model AccessCorpFormulario.Domain.ModelView.CadastroFormularioCampoModelView

@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadasto de Formulario</h2>

<hr />

@using (Html.BeginForm("Cadastro", "Formulario", FormMethod.Post, new { id = "idFormulario" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <fieldset>
            <legend>Informações do Formulário</legend>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.NomeFormulario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NomeFormulario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomeFormulario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataVencimentoInicio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class='input-group'>
                        @Html.EditorFor(model => model.DataVencimentoInicio, new { htmlAttributes = new { @maxlength = 10, @class = "form-control date_time_picker" } })
                        <span id="error-data-vencimento-inicio"
                              class="field-validation-valid text-danger"
                              data-valmsg-replace="true"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataVencimentoFim, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class='input-group'>
                        @Html.EditorFor(model => model.DataVencimentoFim, new { htmlAttributes = new { @maxlength = 10, @class = "form-control date_time_picker" } })
                        <span id="error-data-vencimento-fim"
                              class="field-validation-valid text-danger"
                              data-valmsg-replace="true"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DescricaoFormulario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DescricaoFormulario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DescricaoFormulario, "", new { @class = "text-danger" })
                </div>
            </div>
        </fieldset>
        <hr />
        <fieldset>
            <legend>Campos do Formulário</legend>
            <div class="form-group">
                <label class="control-label col-md-2" for="idTipoCampo">Tipo de Campo</label>
                <div class="col-md-10">
                    @Html.DropDownList("idTipoCampo", new SelectList(Model.ListaTipoCampo, "Value", "Text"), htmlAttributes: new { @class = "control-label col-md-2 select-2" })
                    <div id="addValoresCombo"></div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="idTipoValorCampo">Tipo do valor de campo</label>
                <div class="col-md-10">
                    @Html.DropDownList("idTipoValorCampo", new SelectList(Model.ListaTipoValorCampo, "Value", "Text"), htmlAttributes: new { @class = "control-label col-md-2 select-2" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="ValorCampo"> Valor do Campo</label>
                <div class="col-md-10">
                    <input class="form-control text-box col-md-3" id="ValorCampo" name="ValorCampo" type="text" value="">
                    <input class="btn btn-success col-md-5" type="button" id="btnAdicinarCampoParaCombobox" value="Adicinar o campo para o Combobox" />
                </div>

            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="DescricaoCampo"> Descrição do Campo</label>
                <div class="col-md-10">
                    <input class="form-control text-box col-md-3" id="descricaoCampo" name="DescricaoCampo" type="text" value="">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="button" id="btnAdiconarMaisCampos" value="Adicinar mais campos" class="btn btn-success" />
                </div>
            </div>
            <span id="erro-quantidade-linha-obrigatorio"
                  class="field-validation-valid text-danger"
                  data-valmsg-for="table-campos"
                  data-valmsg-replace="true">É obrigatório adicionar/cadastrar no minímo 10 campos.</span>
            <br />
            <span id="erro-minimo-tres-tipos-distintos-campos"
                  class="field-validation-valid text-danger"
                  data-valmsg-for="table-campos"
                  data-valmsg-replace="true">Você deve cadastrar/adicionar no mínimo três tipos distintos/diferente de campos.</span>

            <table class="table table-bordered table-responsive table-striped" id="table-campos">
                <thead>
                    <tr>
                        <th>Tipo de Campo</th>
                        <th>Tipo do valor de campo</th>
                        <th>Valor do Campo</th>
                        <th>Descrição do Campo</th>
                        <th>Ação</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </fieldset>
        <hr />
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" id="btnSalvar" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Home", "Index")
</div>

AccessCorpFormulario.Web/Views/Formulario/Exibir.cshtml
@model AccessCorpFormulario.Domain.ModelView.FormularioModelView

@{
    ViewBag.Title = "Exibir";
}

<h2>
    Nome do Formulário: @Model.NomeFormulario
</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            <div class="col-md-6">

                <label>Formulário de: @Model.DescricaoFormulario </label>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6">
                <label>Formulário: @Model.Situacao</label>
            </div>
        </div>

        <fieldset>
            <legend></legend>

            @foreach (var formularioCampo in Model.FormularioCampos)
            {
                <hr />
                Html.RenderPartial("_campo", formularioCampo);
            }

        </fieldset>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista", "Lista")
</div>

AccessCorpFormulario.Web/Views/Formulario/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

AccessCorpFormulario.Web/Views/Formulario/Lista.cshtml
@model IEnumerable<AccessCorpFormulario.Domain.ModelView.FormularioModelView>

@{
    ViewBag.Title = "Lista";
}

<h2>Lista</h2>

<p>
    @Html.ActionLink("Criar novo Formulário", "Cadastro")
</p>
<table class="table table-bordered table-responsive table-striped data-table-formulario">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeFormulario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataVencimentoInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataVencimentoFim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Situacao)
            </th>
            <th>
                Ação
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeFormulario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataVencimentoInicio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataVencimentoFim)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Situacao)
                </td>
                <td>
                    @if (item.Ativo)
                    {
                        @Html.ActionLink("Exibir Formulário", "Exibir", new { id = item.IdFormulario })
                    }
                    else
                    {
                        <text>Nenhum</text>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
@section Script{

    <script>
    $(function() {

        var listaFormulario =  '@Html.Raw(Json.Encode(Model.ToList()))';
        $('.data-table-formulario').DataTable({
            "language": {
                "lengthMenu": "Exibe _MENU_ Registros por página",
                "search": "Procurar",
                "paginate": { "previous": "Retorna", "next": "Avança" },
                "zeroRecords": "Nada foi encontrado",
                "info": "Exibindo página _PAGE_ de _PAGES_",
                "infoEmpty": "Sem registros",
                "infoFiltered": "(filtrado de _MAX_ regitros totais)"
            },
            "processing": true, // mostrar a progress bar
            //"serverSide": true, // processamento no servidor
            "filter": true, // habilita o filtro(search box)
            "lengthMenu": [[3, 5, 10, 25, 50, -1], [3, 5, 10, 25, 50, "Todos"]],
            "pageLength": 3, // define o tamanho da página
        });
    });

    </script>
}

AccessCorpFormulario.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/css/datatables.min.css" rel="stylesheet" />
    <link href="~/Content/css/select2.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="logo-acces-corp">
                <img src="~/Content/images/accessPT_vetor_branco.png" />
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>  @Html.ActionLink("Home", "Index", "Formulario", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro", "Cadastro", "Formulario", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Lista de Formulário", "Lista", "Formulario", new { area = "" }, new { @class = "navbar-brand" })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Access Corp</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/datatables.min.js"></script>
    <script src="~/Scripts/select2.min.js"></script>
    <script src="~/Scripts/common.js"></script>
    <script src="~/Scripts/formulario.js"></script>
    <script src="~/Scripts/requestsAPIs.js"></script>

    @RenderSection("Script", required: false)
</body>
</html>

AccessCorpFormulario.Web/Views/Shared/_campo.cshtml
@model AccessCorpFormulario.Domain.ModelView.FormularioCampoModelView

@if (Model.IdTipoCampo == 1)//Textbox
{
    <div class="form-group">
        <label class="control-label col-md-2">@Model.DescricaoCampo</label>
        <div class="col-md-10">
            <div class='input-group'>
                @Html.EditorFor(model => model.IdTipoCampo, new { htmlAttributes = new { @maxlength = 10, @class = "form-control" } })
            </div>
        </div>
    </div>
}
else if (Model.IdTipoCampo == 2)// Dropbox
{
    <div class="form-group">
        <label class="control-label col-md-2">@Model.DescricaoCampo</label>
        <div class="col-md-10">
            <div class='input-group'>
                @Html.DropDownList("idTipoCampo", new SelectList(Model.ValorCampos, "IdValorCampo", "ValorCampo"),"--Selecione--", htmlAttributes: new { @class = "form-control col-md-2  select-2" })
            </div>
        </div>
    </div>
}
else if (Model.IdTipoCampo == 3)//Radio Button
{
    <div class="form-group">
        <label class="control-label col-md-2">@Model.DescricaoCampo</label>
        <div class="col-md-10">
            <div class='input-group'>
                @Html.RadioButtonFor(model => model.IdTipoCampo, new { htmlAttributes = new { @maxlength = 10, @class = "form-control" } })
            </div>
        </div>
    </div>
}